name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build ${{ matrix.framework }}
    runs-on: windows-latest
    strategy:
      matrix:
        framework: [netstandard2.1]

    steps:
    - uses: actions/checkout@v3.5.3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 8.0

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet publish -c Release -f ${{ matrix.framework }} -o "${{github.workspace}}/Release" "NorthwoodLib"
        
    - name: Upload a Build Artifact for ${{ matrix.framework }}
      uses: actions/upload-artifact@v2
      with:
        name: NorthwoodLib-${{ matrix.framework }}
        path: ${{github.workspace}}/Release
