name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test ${{ matrix.framework }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        framework: [netcoreapp3.1]
        include:
        - os: windows-latest
          framework: net472
    env:
      xunitlogpath: ${{github.workspace}}/xunitlog.txt
          
    steps:
    - uses: actions/checkout@v3.5.3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1

    - name: Restore
      run: dotnet restore

    - name: Test
      run: dotnet test -f ${{ matrix.framework }}

    - name: Write log
      run: cat ${{ env.xunitlogpath }}
