name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test ${{ matrix.framework }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        framework: [net8.0]
    env:
      xunitlogpath: ${{github.workspace}}/xunitlog.txt
          
    steps:
    - uses: actions/checkout@v4.1.7

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 8.0

    - name: Restore
      run: dotnet restore

    - name: Test
      run: dotnet test -f ${{ matrix.framework }}

    - name: Write log
      run: cat ${{ env.xunitlogpath }}
